/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_TestJni */

#ifndef _Included_jni_TestJni
#define _Included_jni_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_TestJni
 * Method:    getJniText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_TestJni_getJniText
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
